//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryBase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemoryTag
    {
        public int MemoryTagKey { get; set; }
        public int MemoryKey { get; set; }
        public int TagKey { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual Memory Memory { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
