//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryBase.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class memoryBaseEntities : DbContext
    {
        public memoryBaseEntities()
            : base("name=memoryBaseEntities")
        {
            Database.Log = x => System.Diagnostics.Trace.Write(x);
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emotion> Emotions { get; set; }
        public virtual DbSet<LifeEvent> LifeEvents { get; set; }
        public virtual DbSet<Memory> Memories { get; set; }
        public virtual DbSet<MemoryEmotion> MemoryEmotions { get; set; }
        public virtual DbSet<MemoryLifeEvent> MemoryLifeEvents { get; set; }
        public virtual DbSet<MemoryNote> MemoryNotes { get; set; }
        public virtual DbSet<MemoryPerson> MemoryPersons { get; set; }
        public virtual DbSet<MemoryTag> MemoryTags { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
    }
}
