//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryBase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.MemoryPersons = new HashSet<MemoryPerson>();
        }
    
        public int PersonKey { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateMet { get; set; }
        public Nullable<int> FirstMemoryKey { get; set; }
    
        public virtual Memory Memory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemoryPerson> MemoryPersons { get; set; }
    }
}
